### ISSUE TITLE
HTML tags inside CSV

### ISSUE THREAD

**Issue by makorus** [jwrobb/grav-plugin-table-importer#2]
Hello there,

first of all, thank you SO much for your amazing plugin. Ever since I found it, I've been using it for all sorts of tables!

I recently came across an issue. If I add HTML tags to my CSV file, they aren't being rendered correctly. Instead, the HTML tag is being shown in clear text.

This is the code I use when editing the page:
[ti file="test.csv" header="yes" delimiter="|"]
I also tried this:
[ti file="test.csv" header="yes" delimiter="|" raw="true"]

And this is the content of my CSV file:
Purpose|Template
Welcoming|Hi there and welcome to our group</br></br>To get started...

And this is how it looks like:
![image](https://github.com/user-attachments/assets/1aa0e927-457d-4039-9668-a38ff2223e0f)

Is this a known issue? How can I fix this?

Many thanks in advance!

**Comment by makorus** [comment]
The HTML tags are being rendered by GitHub. between "group" and "to get started", there are two HTML "br" tags.

**Comment by jwrobb** [comment]
Hello! Sorry about the long wait to get back to you. It appears that the "raw" parameter isn't being respected since the `DOM createElement` method escapes any input with no (obvious) way to disable it. I am looking into how to fix this.

**Comment by jwrobb** [comment]
I believe I've corrected the issue. The HTML rendering works in all my tests, but I would be grateful if you tried it out also. 

If you have a development site, or are comfortable testing it live (brave!) you only need to replace the `TableImporterShortcode.php` file in the `user/plugins/table-importer/` within your Grav installation, with the file in this branch:

https://github.com/jwrobb/grav-plugin-table-importer/blob/Issue-2_escaping_all_markup_in_cells/TableImporterShortcode.php

Make sure to create a copy of the original `TableImporterShortcode.php` file before you place that new one in case you need to revert! Empty the Grav cache and hard reload the page. If this fixes the issue I will merge this change into main and release a new point version of the plugin.

**Comment by makorus** [comment]
Works like a charm, wow, thank you so much!!!

**Comment by jwrobb** [comment]
Changes merged and staged for the 3.0.1 bugfix release

https://github.com/jwrobb/grav-plugin-table-importer/pull/3

**Comment by makorus** [comment]
Thank you so much for your amazing work! Happy New Year!

**Comment by makorus** [comment]
Grav Admin Plugin still shows 3.0.0 - how can I update it through the admin panel?
Thank you so much for your amazing work! Happy New Year!

**Comment by jwrobb** [comment]
Thanks for calling this out. I missed updating the `blueprints.yaml` file so the Grav Plugin Manager didn't pick up the update. 🤦 

I've deleted the 3.0.1 release and created a new 3.0.2 release with the corrected blueprints file. This _SHOULD_ fix it so the GPM can update the plugin. Message me again if it isn't being picked up in the next 1-2 days.

**Comment by mesaxians** [comment]
No worries, thank you for your hard work! I just checked my Grav installation and it still shows only 3.0.0 as available; I even tried uninstalling and reinstalling the plugin without success. Any other ideas?

**Comment by makorus** [comment]
No worries, thank you for your hard work! I just checked my Grav installation and it still shows only 3.0.0 as available; I even tried uninstalling and reinstalling the plugin without success. Any other ideas?

**Comment by jwrobb** [comment]
Sorry this took so long but GPM should pick up the new 3.0.1 bugfix release now. Thanks for reporting the issue

**Comment by makorus** [comment]
You're the best, it worked like a charm, the new update just showed up now! Thanks man!
